version: '3.8'

services:
  app:
    build:
      context: .
      target: base
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - ./.docker/dev.env
    command: npm run start
